server:
  port: 8080

spring:
  application:
    name: transaction-system-example
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  web:
    resources:
      static-locations: classpath:/static/


