apiVersion: v1
kind: Service
metadata:
  name: transaction-system-service
spec:
  selector:
    app: transaction-system
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer